### ISSUE TITLE
Invalid scale factor from GLPK solver

### ISSUE THREAD

**Issue by wholtz** [desmondlun/MOST#12]
I am running MOST alpha-12 on linux, without the Gurobi solver.

I imported the Saccharomyces cerevisiae model yeast_7.5 from: http://sourceforge.net/projects/yeast/files/yeast_7.5.zip/download and used the file yeast_7.5/yeast_7.5_cobra.xml from that archive. I left the biological objective == 1.0 for reaction r_2111 (growth), and I set the synthetic objective == 1.0 for reaction r_2057 (succinate transport). I was able to successfully run FBA (without FVA)  and find maximum objective of 0.09469396902139186 using MIL solver GLPK. But when I tried to run GDBB with max knockout = 1 and Indefinate Optimizer Time, I received the following error:

glp_set_rii: i = 6187; rii = 0; invalid scale factor
Error detected in file glpapi04.c at line 45
org.gnu.glpk.GlpkException: function glp_intopt failed
        at org.gnu.glpk.GLPKJNI.glp_intopt(Native Method)
        at org.gnu.glpk.GLPK.glp_intopt(GLPK.java:1223)
        at edu.rutgers.MOST.optimization.solvers.GLPKSolver.optimize(GLPKSolver.java:306)
        at edu.rutgers.MOST.Analysis.GDBB.run(GDBB.java:431)

**Comment by desmondlun** [comment]
Thank you for the bug report! We will look into this and get back to you as
soon as possible. It is currently finals week at the university, so it may
take us a little longer than usual.

Thanks,

Desmond

**Comment by CodeGuro** [comment]
Hello wholtz, thank you for the bug report!
Try replacing all infinite values with 10E3 using Edit -> Find/Replace (attached is the module you should see).
![untitled](https://cloud.githubusercontent.com/assets/2359168/7624045/b052e9be-f9b0-11e4-9893-2088dbf84be1.png)

Then, set the "Find What:" parameter to "Infinity", and the "Replace With:" parameter to "10E6", and select "Find All" and then "Replace All". GLPK and Gurobi should then run without complaints. We'll resolve this tedious issue so it will be done automatically next release.

**Comment by wholtz** [comment]
Thank you for your help CodeGuro. With your instructions I was able to successfully complete a GDBB analysis on my model. It is always great to find open source biotech software that is well supported by the authors!
